services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - chat
      - auth

  chat:
    build:
      context: .
      dockerfile: apps/chat/Dockerfile
    environment:
      MONGO_URL: mongodb://mongo:27017/chat
    depends_on:
      - mongo

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/auth
    depends_on:
      - postgres

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ihavealongpassword
    depends_on:
      - mongo

  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  mongo-data:
  postgres-data: